# NumPy

Read the links: https://numpy.org/doc/stable/user/quickstart.html  and https://numpy.org/doc/stable/user/basics.broadcasting.html  before solving the exercises. 

In [1]:
import numpy as np

### Print out the dimension (number of axes), shape, size and the datatype of the matrix A.

In [2]:
A = np.arange(1, 16).reshape(3,5)
A.ndim
A.shape
A.size
A.dtype


dtype('int64')

### Do the following computations on the matrices B and C: 
* Elementwise subtraction. 
* Elementwise multiplication. 
* Matrix multiplication (by default you should use the @ operator).

In [17]:
B = np.arange(1, 10).reshape(3, 3)
C = np.ones((3, 3))*2


print(A)
print(C)
print(C-B)
print(B * C)
print(B @ C)



[[1 2]
 [3 4]]
[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]
[[ 1.  0. -1.]
 [-2. -3. -4.]
 [-5. -6. -7.]]
[[ 2.  4.  6.]
 [ 8. 10. 12.]
 [14. 16. 18.]]
[[12. 12. 12.]
 [30. 30. 30.]
 [48. 48. 48.]]


### Do the following calculations on the matrix:
* Exponentiate each number elementwise (use the np.exp function).

* Calculate the minimum value in the whole matrix. 
* Calculcate the minimum value in each row. 
* Calculcate the minimum value in each column. 


* Find the index value for the minimum value in the whole matrix (hint: use np.argmin).
* Find the index value for the minimum value in each row (hint: use np.argmin).


* Calculate the sum for all elements.
* Calculate the mean for each column. 
* Calculate the median for each column. 

In [4]:

B = np.arange(1, 10).reshape(3, 3)
Exponent_Value = np.exp(B)
Min_value_Whole_Matrix = np.min(B)
Min_value_row = np.min(B, axis=1)
Min_value_column = np.min(B,axis=0)
find_index_whole_matrix =np.argmin(B)
index_mini_value_row = np.argmin(B, axis=1)
sum_al_elements =B.sum()
mean_each_column = np.mean(B,axis=0 )
meadin_each_column = np.median(B,axis=0 )


print(B)
print(Exponent_Value)
print(Min_value_Whole_Matrix)
print(Min_value_row)
print(Min_value_column)
print(find_index_whole_matrix)
print(index_mini_value_row)
print(sum_al_elements)
print(mean_each_column)
print(meadin_each_column)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[2.71828183e+00 7.38905610e+00 2.00855369e+01]
 [5.45981500e+01 1.48413159e+02 4.03428793e+02]
 [1.09663316e+03 2.98095799e+03 8.10308393e+03]]
1
[1 4 7]
[1 2 3]
0
[0 0 0]
45
[4. 5. 6.]
[4. 5. 6.]


### What does it mean when you provide fewer indices than axes when slicing? See example below.

In [5]:
print(A)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [6]:
A[1]

array([ 6,  7,  8,  9, 10])

**Answer:**
Numpy behandlar som ett tecken de saknade indexen på dimension

### Iterating over multidimensional arrays is done with respect to the first axis, so in the example below we iterate trough the rows. If you would like to iterate through the array *elementwise*, how would you do that?

In [7]:
A

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [8]:
for i in A:
    print(i)

[1 2 3 4 5]
[ 6  7  8  9 10]
[11 12 13 14 15]


We can iterate elementwise through the entire array. We can use nditer function from numpy to allow element by element.

### Explain what the code below does. More specifically, b has three axes - what does this mean? 

In [9]:
a = np.arange(30)
b = a.reshape((2, 3, -1))
print(a)
print()

print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]


a = np.arange(30) : Creates numpy array a with 0 to 29 ranging 30 elements.

b = a.reshape((2, 3, -1)): reshape the a with 3 dimensional array b where 2 indicates first axis size of outer arraay. 3 indicate second axis size of three and and it contains three arrays. -1 indicate that numpy automatically calculate the size of third axis it depends of the how much elements of the array. in this case total elements 30 divided by 6(2*3). So column become 5.
we can say reshape becomes (2, 3, 5).




### Broadcasting
**Read the following link about broadcasting: https://numpy.org/doc/stable/user/basics.broadcasting.html#basics-broadcasting**

# Remark on Broadcasting when doing Linear Algebra calculations in Python. 

### From the mathematical rules of matrix addition, the operation below (m1 + m2) does not make sense. The reason is that matrix addition requires two matrices of the same size. In Python however, it works due to broadcasting rules in NumPy. So you must be careful when doing Linear Algebra calculations in Python since they do not follow the "mathematical rules". This can however easily be handled by doing some simple programming, for example validating that two matrices have the same shape is easy if you for instance want to add two matrices. 

In [10]:
m1 = np.array([[1, 2], [3, 4]])
m2 = np.array([1, 1])
print(m1 + m2)

[[2 3]
 [4 5]]


### The example below would also not be allowed if following the "mathematical rules" in Linear Algebra. But it works due to broadcasting in NumPy. 

In [11]:
v1 = np.array([1, 2, 3])
print(v1 + 1)

[2 3 4]


In [12]:
A = np.arange(1, 5).reshape(2,2)
print(A)

b = np.array([2, 2])
print(b)

[[1 2]
 [3 4]]
[2 2]


# Vector- and matrix algebra Exercises

**Now you are going to create a function that can be reused every time you add or multiply matrices. The function is created so that we do the addition and multiplication according to the rules of vector- and matrix algebra.**

**Create a function "add_mult_matrices" that takes two matrices as input arguments (validate that the input are of the type numpy.ndarray by using the isinstance function), a third argument that is either 'add' or 'multiply' that specifies if you want to add or multiply the matrices (validate that the third argument is either 'add' or 'multiply'). When doing matrix addition, validate that the matrices have the same size. When doing matrix multiplication, validate that the sizes conform (i.e. number of columns in the first matrix is equal to the number of rows in the second matrix).**

In [36]:
import numpy as np
def add_mult_matrics(matrics_A, matrics_B, Sum_matrics):
    
    if not isinstance(matrics_A, np.ndarray) or not isinstance(matrics_B, np.ndarray):
        raise TypeError("Please write the correct numpy array")     
    
    if Sum_matrics == "add":
        if matrics_A.shape != matrics_B.shape:
            raise ValueError("value should be same size")
        return np.add(matrics_A,matrics_B)  
    elif Sum_matrics == "multiply":
        if matrics_A.shape[0] != matrics_B.shape[1]:
            raise ValueError("number of column in first matrix should be equal")            
        return np.dot(matrics_A,matrics_B)
    else:
        raise ValueError("add / multiply")
    
    
    
matrics_A = np.array([[10, 20], [30, 40]])
matrics_B = np.array([[50, 60], [70, 80]])
    
Addition = add_mult_matrics(matrics_A, matrics_B,"add")
print(f"Addition{Addition}")
    
Multiplication = add_mult_matrics(matrics_A,matrics_B,"multiply")
print(f"Multiplication: {Multiplication}")
    

Addition[[ 60  80]
 [100 120]]
Multiplication: [[1900 2200]
 [4300 5000]]


### Solve all the exercises in chapter 10.1 in the book "Matematik för yrkeshögskolan". 

Uppgift 10.1.1:
a. vilken dimension har vektorn x?
Svar:Vektorn har 2 dimension eftersom vektorn har 2 komponenter.

b.Beräkna 5x.
Svar:5x = 5.(4,3) = (20,15)

c. Beräkna 3x.
Svar: 3x = 3.(4,3) = (12,9)

d. Beräkna 5x + 3x

Svar: 5x + 3x = (20,15) + (12,9) = (32,24)

e.Beräkna 8x.
Svar: 8x = 8.(4,3) (32,24)

f. Beräkna 4x-x
Svar: 4x-x = 4.(4,3)- (4,3) = (16,12) - (4,3) =(12,9)

g. Beräkna X^T, vilket blir nya dimensionen efter att transponeringen utförts?
Svar: The vektor x = (4,3), Så ändrar det rad till kolumn vektor  x^T = 4/3. Så ny dimension blir 2X1 kolumn vektor.

h. Är x + x^T definerat.
Svar: Nej. Rad och kolumn vektors dimension matchar inte. Så Rad och kolumn vektor definerar inte i matrix.

i. Beräkna ||x||.
Svar: Root4^2 + Root3^2 = Root25 = 5



10.1.2. Definera vektorn v enligt nedan.
V = (3
     7
     0
     11)

a. Vilken dimension har vektorn v?
Svar:Vektorn har 4 dimension eftersom vektorn har 4 komponenter.

b.Beräkna 2v.
2V = (6
      14
      0
      22)

c. Beräkna 5v + 2v
Svar: 5v + 2v = (21
                 49
                 0
                 77)

d. Beräkna 4v- 2v
Svar:           
       4v-2v =  (6
                 14
                 0
                 22)

e.Beräkna V^T vilken blir nya dimension.
Svar: V^T = (3,7,0,11)
Ny dimension blir 1x4.

f. Beräkna ||v||
Svar: ||v|| = Root(3^2 + 7^2 + 11^2)= root(179)= 13.38


Uppgift 10.1.3:

a. Beräkna ||v1||.
v1 = root(4^1 + 3^2 + 1.5^2) = root(27.25)=5.22

b. Beräkna || v1 - v2||
|| v1 - v2|| = root(4.16)~~2.04




        





### Solve all the exercises, except 10.2.4, in chapter 10.2 in the book "Matematik för yrkeshögskolan". 

Uppgift 10.2.1. Definera matriserna.

a. Svar:2A =2.(2  1  -1)
          (1  1  1)
          (-1  0  1)
      
       = (4   1   -2)
        (2   2    2)
        (-2  0    2)


b. B-2A
Svar: B är en 2 X 3 matris och 2A är 3 X 3 matris. Så vi kan inte räkna för detta är inte definerat.

c. 3C -2E
Svar:C är 2 x 2 matris och E är 1 X 1 vektor. Detta är inte definerat eftersom dimension matchar inte.

d. 2D-3C
Svar: 2D - 3c = (6  8)   -  (1.5 1.5)
                (6  6)       (1.5 1.5)
              

              = (4.5   6.5)
                (4.5   4.5)



e. D^T + 2D 
Svar: D^T + 2D = (9   11)
                 (10   9)




f. 2C^T -2D^-1
Svar: 2C^T -2D^-1 =  (3  -5/8)
                     (-1    3)



g.A^T - B

Svar:A^T = ( 2   1   -1)
           (1    1   0)
           (-1   1    1)

matris B är 2 X 3 och A^T 3 X 3. Så dimension matchar inte och detta är inte definerat.

**Basic indexing creates a view, How can you check if v1 and v2 is a view or copy? If you change the last element in v2 to 123, will the last element in v1 be changed? Why?**

### Copies and Views
Read the following link: https://numpy.org/doc/stable/user/basics.copies.html

In [42]:
v1 = np.arange(4)
v2 = v1[-2:]
print(v1)
print(v2)

[0 1 2 3]
[2 3]


In [43]:
# The base attribute of a view returns the original array while it returns None for a copy.
print(v1.base)
print(v2.base)
print(v2.base is None)
print(v1.base is None)

None
[0 1 2 3]
False
True


In [15]:
# The last element in v1 will be changed aswell since v2 is a view, meaning they share the same data buffer.
v2[-1] = 123
print(v1)
print(v2)

[  0   1   2 123]
[  2 123]
